import { SurveyQuestion } from '@/types/survey';

export const CURRENT_SURVEY_VERSION = 'survey_v1';
export const CURRENT_POLICY_VERSION = 'tribhuban_retailer_policy_v1_2026';

export const CONSENT_DISCLAIMER_TEXT =
  'I confirm that the information provided is accurate and consent to Tribhuban Concepts contacting me regarding retail partnership opportunities. I understand and acknowledge that this survey is for business qualification and relationship planning only, and DOES NOT constitute an application, offer, guarantee, underwriting, or approval for any bank loan, credit facility, insurance product, or third-party financial service.';

export const SURVEY_V1_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'q_understanding_clarity',
    survey_version: 'survey_v1',
    section: 'Understanding',
    question_text: 'How clear is the Tribhuban business model?',
    question_type: 'single_choice',
    order_index: 1,
    is_required: true,
    options: [
      { id: 'opt_uc_1', question_id: 'q_understanding_clarity', option_label: 'Very clear', option_value: 'VERY_CLEAR', order_index: 1 },
      { id: 'opt_uc_2', question_id: 'q_understanding_clarity', option_label: 'Mostly clear', option_value: 'MOSTLY_CLEAR', order_index: 2 },
      { id: 'opt_uc_3', question_id: 'q_understanding_clarity', option_label: 'Somewhat clear', option_value: 'SOMEWHAT_CLEAR', order_index: 3 },
      { id: 'opt_uc_4', question_id: 'q_understanding_clarity', option_label: 'Not clear', option_value: 'NOT_CLEAR', order_index: 4 },
    ],
  },
  {
    id: 'q_understanding_explanation',
    survey_version: 'survey_v1',
    section: 'Understanding',
    question_text: 'What needs more explanation?',
    question_type: 'multi_choice',
    order_index: 2,
    is_required: false,
    options: [
      { id: 'opt_ue_1', question_id: 'q_understanding_explanation', option_label: 'Products', option_value: 'PRODUCTS', order_index: 1 },
      { id: 'opt_ue_2', question_id: 'q_understanding_explanation', option_label: 'Pricing', option_value: 'PRICING', order_index: 2 },
      { id: 'opt_ue_3', question_id: 'q_understanding_explanation', option_label: 'Bundles', option_value: 'BUNDLES', order_index: 3 },
      { id: 'opt_ue_4', question_id: 'q_understanding_explanation', option_label: 'Sales process', option_value: 'SALES_PROCESS', order_index: 4 },
      { id: 'opt_ue_5', question_id: 'q_understanding_explanation', option_label: 'Customer acquisition', option_value: 'CUSTOMER_ACQUISITION', order_index: 5 },
      { id: 'opt_ue_6', question_id: 'q_understanding_explanation', option_label: 'Online orders', option_value: 'ONLINE_ORDERS', order_index: 6 },
      { id: 'opt_ue_7', question_id: 'q_understanding_explanation', option_label: 'Delivery', option_value: 'DELIVERY', order_index: 7 },
      { id: 'opt_ue_8', question_id: 'q_understanding_explanation', option_label: 'Retailer benefits', option_value: 'RETAILER_BENEFITS', order_index: 8 },
      { id: 'opt_ue_9', question_id: 'q_understanding_explanation', option_label: 'Partner benefits', option_value: 'PARTNER_BENEFITS', order_index: 9 },
      { id: 'opt_ue_10', question_id: 'q_understanding_explanation', option_label: 'Other', option_value: 'OTHER', order_index: 10 },
    ],
  },
  {
    id: 'q_interest_level',
    survey_version: 'survey_v1',
    section: 'Interest',
    question_text: 'Level of interest in Tribhuban partnership:',
    question_type: 'single_choice',
    order_index: 3,
    is_required: true,
    options: [
      { id: 'opt_il_1', question_id: 'q_interest_level', option_label: 'Definitely interested', option_value: 'DEFINITELY_INTERESTED', order_index: 1 },
      { id: 'opt_il_2', question_id: 'q_interest_level', option_label: 'Interested', option_value: 'INTERESTED', order_index: 2 },
      { id: 'opt_il_3', question_id: 'q_interest_level', option_label: 'Need more information', option_value: 'NEED_MORE_INFORMATION', order_index: 3 },
      { id: 'opt_il_4', question_id: 'q_interest_level', option_label: 'Not currently interested', option_value: 'NOT_CURRENTLY_INTERESTED', order_index: 4 },
    ],
  },
  {
    id: 'q_readiness_timeline',
    survey_version: 'survey_v1',
    section: 'Readiness',
    question_text: 'Expected readiness timeline:',
    question_type: 'single_choice',
    order_index: 4,
    is_required: true,
    options: [
      { id: 'opt_rt_1', question_id: 'q_readiness_timeline', option_label: 'Immediately', option_value: 'IMMEDIATELY', order_index: 1 },
      { id: 'opt_rt_2', question_id: 'q_readiness_timeline', option_label: 'Within 1 month', option_value: 'WITHIN_1_MONTH', order_index: 2 },
      { id: 'opt_rt_3', question_id: 'q_readiness_timeline', option_label: 'Within 1–3 months', option_value: 'WITHIN_1_3_MONTHS', order_index: 3 },
      { id: 'opt_rt_4', question_id: 'q_readiness_timeline', option_label: 'Later', option_value: 'LATER', order_index: 4 },
      { id: 'opt_rt_5', question_id: 'q_readiness_timeline', option_label: 'Not sure', option_value: 'NOT_SURE', order_index: 5 },
    ],
  },
  {
    id: 'q_concern_categories',
    survey_version: 'survey_v1',
    section: 'Concerns',
    question_text: 'Primary concern categories:',
    question_type: 'multi_choice',
    order_index: 5,
    is_required: true,
    options: [
      { id: 'opt_cc_1', question_id: 'q_concern_categories', option_label: 'Product quality', option_value: 'PRODUCT_QUALITY', order_index: 1 },
      { id: 'opt_cc_2', question_id: 'q_concern_categories', option_label: 'Pricing', option_value: 'PRICING', order_index: 2 },
      { id: 'opt_cc_3', question_id: 'q_concern_categories', option_label: 'Margin/benefit', option_value: 'MARGIN_BENEFIT', order_index: 3 },
      { id: 'opt_cc_4', question_id: 'q_concern_categories', option_label: 'Customer demand', option_value: 'CUSTOMER_DEMAND', order_index: 4 },
      { id: 'opt_cc_5', question_id: 'q_concern_categories', option_label: 'Delivery', option_value: 'DELIVERY', order_index: 5 },
      { id: 'opt_cc_6', question_id: 'q_concern_categories', option_label: 'Product availability', option_value: 'PRODUCT_AVAILABILITY', order_index: 6 },
      { id: 'opt_cc_7', question_id: 'q_concern_categories', option_label: 'Payment process', option_value: 'PAYMENT_PROCESS', order_index: 7 },
      { id: 'opt_cc_8', question_id: 'q_concern_categories', option_label: 'Technology/platform', option_value: 'TECHNOLOGY_PLATFORM', order_index: 8 },
      { id: 'opt_cc_9', question_id: 'q_concern_categories', option_label: 'Returns/replacements', option_value: 'RETURNS_REPLACEMENTS', order_index: 9 },
      { id: 'opt_cc_10', question_id: 'q_concern_categories', option_label: 'Competition with existing business', option_value: 'COMPETITION_EXISTING', order_index: 10 },
      { id: 'opt_cc_11', question_id: 'q_concern_categories', option_label: 'Operational workload', option_value: 'OPERATIONAL_WORKLOAD', order_index: 11 },
      { id: 'opt_cc_12', question_id: 'q_concern_categories', option_label: 'Partner/finance process', option_value: 'PARTNER_FINANCE_PROCESS', order_index: 12 },
      { id: 'opt_cc_13', question_id: 'q_concern_categories', option_label: 'Insurance-related process', option_value: 'INSURANCE_PROCESS', order_index: 13 },
      { id: 'opt_cc_14', question_id: 'q_concern_categories', option_label: 'Other', option_value: 'OTHER', order_index: 14 },
    ],
  },
  {
    id: 'q_main_concern_description',
    survey_version: 'survey_v1',
    section: 'Concerns',
    question_text: 'Please describe your main concern.',
    question_type: 'text',
    order_index: 6,
    is_required: true,
  },
  {
    id: 'q_useful_expectations',
    survey_version: 'survey_v1',
    section: 'Expectations',
    question_text: 'What would make Tribhuban more useful for your business?',
    question_type: 'text',
    order_index: 7,
    is_required: true,
  },
  {
    id: 'q_platform_expectations',
    survey_version: 'survey_v1',
    section: 'Expectations',
    question_text: 'Platform expectations:',
    question_type: 'multi_choice',
    order_index: 8,
    is_required: true,
    options: [
      { id: 'opt_pe_1', question_id: 'q_platform_expectations', option_label: 'Easy ordering', option_value: 'EASY_ORDERING', order_index: 1 },
      { id: 'opt_pe_2', question_id: 'q_platform_expectations', option_label: 'Product catalogue', option_value: 'PRODUCT_CATALOGUE', order_index: 2 },
      { id: 'opt_pe_3', question_id: 'q_platform_expectations', option_label: 'Sales tracking', option_value: 'SALES_TRACKING', order_index: 3 },
      { id: 'opt_pe_4', question_id: 'q_platform_expectations', option_label: 'Offers/promotions', option_value: 'OFFERS_PROMOTIONS', order_index: 4 },
      { id: 'opt_pe_5', question_id: 'q_platform_expectations', option_label: 'Customer management', option_value: 'CUSTOMER_MANAGEMENT', order_index: 5 },
      { id: 'opt_pe_6', question_id: 'q_platform_expectations', option_label: 'Delivery support', option_value: 'DELIVERY_SUPPORT', order_index: 6 },
      { id: 'opt_pe_7', question_id: 'q_platform_expectations', option_label: 'Business insights', option_value: 'BUSINESS_INSIGHTS', order_index: 7 },
      { id: 'opt_pe_8', question_id: 'q_platform_expectations', option_label: 'Support/contact', option_value: 'SUPPORT_CONTACT', order_index: 8 },
      { id: 'opt_pe_9', question_id: 'q_platform_expectations', option_label: 'Rewards/referrals', option_value: 'REWARDS_REFERRALS', order_index: 9 },
      { id: 'opt_pe_10', question_id: 'q_platform_expectations', option_label: 'Notifications', option_value: 'NOTIFICATIONS', order_index: 10 },
      { id: 'opt_pe_11', question_id: 'q_platform_expectations', option_label: 'Other', option_value: 'OTHER', order_index: 11 },
    ],
  },
  {
    id: 'q_suggestion_change',
    survey_version: 'survey_v1',
    section: 'Suggestions',
    question_text: 'If you could change one thing about this business model, what would it be?',
    question_type: 'text',
    order_index: 9,
    is_required: false,
  },
];
